// apps/test-react/src/components/MyForm.tsx
import React, { useState } from 'react';

export default function MyForm() {
    const [email, setEmail] = useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        console.log("Submitted with email", email);
    }

    return (
        <form id="react-contact-form" onSubmit={handleSubmit}>
            <h2>React Test Form</h2>
            <input type="email" placeholder="Email Address" value={email} onChange={e => setEmail(e.target.value)} />
            <button type="submit" className="submit-btn text-white bg-blue-500 p-2 m-2">Submit</button>
        </form>
    )
}

// apps/test-vue/src/components/MyForm.vue
<script setup lang="ts">
import { ref } from 'vue';

const email = ref('');
const handleSubmit = () => {
    console.log("Submitted with email", email.value);
};
</script>

<template>
    <form id="vue-contact-form" @submit.prevent="handleSubmit">
        <h2>Vue Test Form</h2>
        <input type="email" placeholder="Email Address" v-model="email" />
        <button type="submit" class="submit-btn text-white bg-green-500 p-2 m-2">Submit</button>
    </form>
</template>
